# 
# SECURITY 
#
# This file defines a sequential set of security rules which should
# be applied to the project.
#
# @NOTE while it is not considered secure to use a local file to 
#   manage local security, this file will also used as an import
#   source for application of these rules in a production environment
#   where the yml may get imported into any config source.
#

orchestrate.up:
	security.user:
		- *

upcloud.server.start:
	security.user: 
		- jamesnesbitt
		- aleksijohansson
	upcloud.server.label:
	- this-project

upcloud.server.stop:
	security.user: 
		- jamesnesbitt
		- aleksijohansson
	upcloud.server.uuid:
		- AAAAAAA-AAAAAAA-AAAAA
		- BBBBBBB-BBBBBBB-BBBBB
	