application:
  environment: 'local'
  language: 'en'
  editor: 'vim'
  temp: '/tmp'
  develop: 'true'
  command: 'about'
  checked: 'false'
  # remote:
  #   user: 'root'
  #   port: '22'
  #   console: '/usr/local/bin/drupal'
  #   keys:
  #     public: '~/.ssh/id_rsa.pub'
  #     private: '~/.ssh/id_rsa'
  #     passphrase: '~/.ssh/passphrase.txt'
  composer:
    create-project:
      default:
#          repository: 'https://packagist.org'
        package: 'drupal-composer/drupal-project'
      drupal:
#          repository: 'https://packagist.org'
        package: 'drupal/drupal'
    repositories:
      default: 'https://packagist.drupal-composer.org'
      drupal: 'https://packages.drupal.org/8'
      packagist: 'https://packagist.org'
  disable:
    modules: []
    commands: []
    namespaces: []
  options:
    learning: false
    examples: false
    generate-inline: false
    generate-chain: false
    composer: false
    shellexec_output: false